name: first

on:
  push: 
    branches: python_sample

jobs:
 ubuntu:
  runs-on: ubuntu-latest
  steps:
  - name: Step one
    run: |
        ls -ltr
        java -version
  
 windows:
  runs-on: windows-latest
  steps:
  - name: Step one
    run: date      

 mac:
  runs-on: macos-latest
  steps:
  - name: Step one
    run: date
  
 overall:
  needs: [ubuntu, windows, mac]
  runs-on: ubuntu-latest
  steps:
  - name: Step one
    run: date
